title = "Leonardo Biason"

[params.author]
name = "Leonardo Biason"
image = "img/pfp.jpg"
headline = "_the stephen hawkings of bad ideas_"
links = [
  { linkedin = "https://www.linkedin.com/in/leonardobiason/" },
  { github = "https://github.com/ElBi21" }
]
