[markup]
	[markup.goldmark]
		renderer.unsafe = true

[module]
    [[module.mounts]]
        source = "assets/icons"
        target = "static/icons"

    [[module.mounts]]
        source = "assets/img"
        target = "static/img"

    [[module.mounts]]
        source = "assets/pdfs"
        target = "static/attachments"

    [[module.mounts]]
        source = "static"
        target = "static"