on: push
name: Deploy on FTP server 
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/main'
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        dry-run: false
        server-dir: ${{ secrets.ftp_dir }}
        exclude: |
          **/.git*
          **/.git*/**
          **/.idea/**
          README.md
