on:
  push:
    branches:
      - "main"

name: Build and Deploy on FTP server

jobs:
  build-deploy:
    name: Compile the Nuxt site and push it to the FTP server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Install Node.js dependencies
        run: |
          bun install

      - name: Build static website
        run: |
          bun run generate

      - name: Copy htaccess
        run: "cp .htaccess output/public/.htaccess"

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          dry-run: false
          local-dir: ./output/public/
          server-dir: ${{ secrets.ftp_dir }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.idea/**
            README.md
